basePath: /
definitions:
  info.IdPwd:
    properties:
      id:
        type: string
      password:
        type: string
    type: object
  info.Info:
    properties:
      email:
        type: string
      first_name:
        type: string
      gender:
        type: string
      id:
        type: integer
      ip_address:
        type: string
      last_name:
        type: string
    type: object
  login.loginInfo:
    properties:
      id:
        type: string
      password:
        type: string
    type: object
  signup.User:
    properties:
      addr:
        type: string
      email:
        type: string
      id:
        type: string
      password:
        type: string
      phone_number:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fiber Example API
  version: "1.0"
paths:
  /info:
    get:
      description: get accounts
      produces:
      - application/json
      responses: {}
      summary: List accounts
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: post accounts
      parameters:
      - description: good
        in: body
        name: Data
        required: true
        schema:
          $ref: '#/definitions/info.Info'
      produces:
      - application/json
      responses: {}
      summary: post accounts
      tags:
      - Users
  /login:
    post:
      consumes:
      - application/json
      description: check id and password
      parameters:
      - description: annoying
        in: body
        name: login_info
        required: true
        schema:
          $ref: '#/definitions/login.loginInfo'
      produces:
      - application/json
      responses: {}
      summary: login
      tags:
      - login
  /signup:
    post:
      description: Post user info
      parameters:
      - description: User infomation
        in: body
        name: Info
        required: true
        schema:
          $ref: '#/definitions/signup.User'
      responses: {}
      summary: Sign up
      tags:
      - SignUp
  /test:
    post:
      consumes:
      - application/json
      description: Test get list
      parameters:
      - description: annoying
        in: body
        name: login_info
        required: true
        schema:
          $ref: '#/definitions/info.IdPwd'
      produces:
      - application/json
      responses: {}
      summary: Test List
      tags:
      - Test
swagger: "2.0"
